### ISSUE TITLE
In advisor view, Plan search results should be sorted by Time Updated from latest to earliest

### ISSUE THREAD

**Issue by philectron** [osu-capstone-cs72/cs-applied-plan-portal#87]
Treat this as a refactor request, not a bug.

## Repro Step

1. Launch app
2. Log in as an Advisor
3. Search for some Plans

## Expected results:

By default, Plan results should be sorted by `Time Updated` in descending order, i.e. later changed Plans should be put above earlier changed Plans.

![image](https://user-images.githubusercontent.com/14208546/81754928-3680a200-946c-11ea-8dce-1d58dd6335f2.png)

## Actual results:

Plan results are sorted by `Time Updated` in ascending order, i.e. later changed Plans are currently below earlier changed Plans.

![image](https://user-images.githubusercontent.com/14208546/81754900-2072e180-946c-11ea-9bd6-680e49a93907.png)

**Comment by silverware13** [comment]
I now recall why I set it up this way.

My assumption is that advisors will spend most of their time in app using search to find plans to review.

So for example they may want to go through all of the plans with the status "Awaiting Review"

In that instance it is better to show older plans, not newer plans. Otherwise old plans would never get reviewed.
